### ISSUE TITLE
aggregationFunction: "sum" return wrong results for specific facts

### ISSUE THREAD

**Issue by ghost** [28msec/cellstore-csharp#61]
Hi,
When i run this code i get correct results for almost all the facts except for few examples where the results are wrong.
I checked the input archives facts and they just not sum up to the result.

Dictionary> dimensions = new Dictionary> 
{ { "boi:FilingStatus", new List { "ALL" } } };
Dictionary dimensionsVisible = new Dictionary 
{ { "xbrl:Entity::visible", true } };
Dictionary dimensionsCategory = new Dictionary 
{ { "xbrl:Entity::category", "slicer" } };
List aid = directiveCalculationDocumet.membersAID.Select(x => x.AID).ToList();

dynamic facts = dataAPI.GetFacts(token: token, labels: false, dimensions: dimensions, aid: aid, dimensionsCategory: dimensionsCategory, aggregationFunction: "sum", open: true);

**Comment by fcavalieri** [comment]
Hello @amit-boi, could you provide us more information (e.g. aids,concepts...) about which archives trigger this problem?
Thanks

**Comment by ghost** [comment]
The only parameter that i supply to the GetFacts function except for the ones i noted already is a List<string> of archive ids :
"10001_D822_2016-01-01_2016-03-31_20160706160706000"
"11001_D822_2016-01-01_2016-03-31_20160705120116185"
"12001_D822_2016-01-01_2016-03-31_20160706103358000"
"20001_D822_2016-01-01_2016-03-31_20160705135745347"
"31001_D822_2016-01-01_2016-03-31_20160705121030184"

**Comment by fcavalieri** [comment]
Hello Amit,

thank you for the bug report. Would it be possible for us to have these
filings?
It would be really helpful to both reproduce this issue and for general
unit testing.

I explicitly added your email address, let me know if you prefer that this
or if you rely only on the github notifications.

Thanks and kind regards,
Federico

**Comment by fcavalieri** [comment]
Hello Amit,
could you also give us some pointers to identify the wrongly computed fact?

Thanks and kind regards,
Federico

**Comment by ghost** [comment]
Hi,
I put in the privateArk the five source archives as they where reported by the banks inorder for you to duplicate the summary problem.

Example of the first summary problem is showen below.
The sumarry fact value should be 78763653 by summary of the relevent banks facts
respectively (31001 + 20001 + 12001 + 11001 + 10001):
7616697 + 26957774 + 15027423 + 9607580 + 19554179

![summary problem](https://cloud.githubusercontent.com/assets/20640298/18118080/6501e146-6f5b-11e6-9041-88e02aea5522.jpg)

**Comment by fcavalieri** [comment]
Hello Amit,

@wcandillon and I tried to reproduce the issue on our side.

We first retrieved the five facts from your five archive that correspond to "Thereof: fixed  interest credit"

http://<...>/v1/_queries/public/api/facts.jq?token=foobar&boi:FilingStatus=ALL&aid=10001_D822_2016-01-01_2016-03-31_20160706160706000&aid=11001_D822_2016-01-01_2016-03-31_20160705120116185&aid=12001_D822_2016-01-01_2016-03-31_20160706103358000&aid=20001_D822_2016-01-01_2016-03-31_20160705135745347&aid=31001_D822_2016-01-01_2016-03-31_20160705121030184&boi_dim:BCC=boi_bc:x1&boi_dim:SEC=boi_se:x16&boi_dim:CSC=boi_cs:x1&boi_dim:MCI=boi_mc:x962&boi_dim:CUO=boi_cu:x5&boi_dim:MCC=boi_mc:x297&boi_dim:CUI=boi_cu:x23&boi_dim:GAA=boi_ga:x1&concept=boi_met:md87&open=true&format=html

This gave us the five facts with the value you reported:
![image](https://cloud.githubusercontent.com/assets/4959269/18205958/fa453de6-7124-11e6-838e-5a5c57bc4bd6.png)

We then enabled the aggregation, as in your code:

http://<>/v1/_queries/public/api/facts.jq?token=foobar&boi:FilingStatus=ALL&aid=10001_D822_2016-01-01_2016-03-31_20160706160706000&aid=11001_D822_2016-01-01_2016-03-31_20160705120116185&aid=12001_D822_2016-01-01_2016-03-31_20160706103358000&aid=20001_D822_2016-01-01_2016-03-31_20160705135745347&aid=31001_D822_2016-01-01_2016-03-31_20160705121030184&boi_dim:BCC=boi_bc:x1&boi_dim:SEC=boi_se:x16&boi_dim:CSC=boi_cs:x1&boi_dim:MCI=boi_mc:x962&boi_dim:CUO=boi_cu:x5&boi_dim:MCC=boi_mc:x297&boi_dim:CUI=boi_cu:x23&boi_dim:GAA=boi_ga:x1&concept=boi_met:md87&open=true&format=html&aggregation-function=sum&xbrl:Entity::category=slicer

This gave us the sum that you expect:

![image](https://cloud.githubusercontent.com/assets/4959269/18206018/3d789dce-7125-11e6-85ee-a2425134a316.png)

We also tried to do the same exact request that you did:
http://<>/v1/_queries/public/api/facts.jq?token=foobar&labels=false&boi:FilingStatus=ALL&aid=10001_D822_2016-01-01_2016-03-31_20160706160706000&aid=11001_D822_2016-01-01_2016-03-31_20160705120116185&aid=12001_D822_2016-01-01_2016-03-31_20160706103358000&aid=20001_D822_2016-01-01_2016-03-31_20160705135745347&aid=31001_D822_2016-01-01_2016-03-31_20160705121030184&xbrl:Entity::category=slicer&xbrl:Entity::visible=true&aggregation-function=sum&open=true&format=html

This gave us a long list of facts including the one with the sum that you expect:
![image](https://cloud.githubusercontent.com/assets/4959269/18206178/c535a702-7125-11e6-8afc-5f8e86b82409.png)

So, we cannot reproduce the issue.
If you run these three requests on your side what do you get?
How did you produce the spreadsheet for component that i see in the bug report?

Kind regards,
Federico

**Comment by ghost** [comment]
Hello Federico,
I found a bug in my code that caused this problem.
Thank you very much for the assistance in resolving this issue :)
