### ISSUE TITLE
Allow multiple values for a single dimension

### ISSUE THREAD

**Issue by dknochen** [28msec/cellstore-csharp#8]
The rest API allows you to ask for several dimension members at once. For example:

xbrl:FiscalYear=2014&xbrl:FiscalYear=2015

Yet, Dictionary allows only one value per key.

Any idea how to solve this?

**Comment by fcavalieri** [comment]
Hi @dknochen , do you confirm this is fixed in 2.0.1 and later?

**Comment by dknochen** [comment]
@fcavalieri yes, thank you
